"""add consignment_items.placeholder_name

Revision ID: 30f43e27432e
Revises: 649ad335f0f1
Create Date: 2026-08-26 18:07:34.614550

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '30f43e27432e'
down_revision: Union[str, Sequence[str], None] = '649ad335f0f1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('consignment_items', sa.Column('placeholder_name', sa.String(length=255), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('consignment_items', 'placeholder_name')
    # ### end Alembic commands ###
