"""notification delivery group_key

Revision ID: 3142a00a5b31
Revises: e42775a85496
Create Date: 2026-08-28 17:47:12.657128

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3142a00a5b31'
down_revision: Union[str, Sequence[str], None] = 'e42775a85496'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('notification_deliveries', sa.Column('group_key', sa.String(length=255), nullable=True))
    op.create_index('ix_notification_deliveries_user_created', 'notification_deliveries', ['user_id', 'created_at'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_notification_deliveries_user_created', table_name='notification_deliveries')
    op.drop_column('notification_deliveries', 'group_key')
    # ### end Alembic commands ###
