"""index logistics_items consignment_id and job_no for list filters

Revision ID: 54bba93ee1c1
Revises: 30f43e27432e
Create Date: 2026-08-26 19:10:33.395369

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '54bba93ee1c1'
down_revision: Union[str, Sequence[str], None] = '30f43e27432e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_logistics_items_consignment_id'), 'logistics_items', ['consignment_id'], unique=False)
    op.create_index(op.f('ix_logistics_items_job_no'), 'logistics_items', ['job_no'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_logistics_items_job_no'), table_name='logistics_items')
    op.drop_index(op.f('ix_logistics_items_consignment_id'), table_name='logistics_items')
    # ### end Alembic commands ###
