"""trucking source_ref index and logistics sent_to_trucking_at

Revision ID: 649ad335f0f1
Revises: b9f72f7a8a7e
Create Date: 2026-08-25 15:46:21.519553

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '649ad335f0f1'
down_revision: Union[str, Sequence[str], None] = 'b9f72f7a8a7e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('logistics_consignments', sa.Column('sent_to_trucking_at', sa.DateTime(timezone=True), nullable=True))
    op.create_index(op.f('ix_logistics_consignments_sent_to_trucking_at'), 'logistics_consignments', ['sent_to_trucking_at'], unique=False)
    op.create_index('ix_trucking_consignments_source_ref', 'trucking_consignments', ['source', 'source_ref'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_trucking_consignments_source_ref', table_name='trucking_consignments')
    op.drop_index(op.f('ix_logistics_consignments_sent_to_trucking_at'), table_name='logistics_consignments')
    op.drop_column('logistics_consignments', 'sent_to_trucking_at')
    # ### end Alembic commands ###
