"""notification tables, catalogue support and user notification fields

Revision ID: 8ad6b97f1997
Revises: 54bba93ee1c1
Create Date: 2026-08-28 12:20:40.113934

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8ad6b97f1997'
down_revision: Union[str, Sequence[str], None] = '54bba93ee1c1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('notification_events',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('event_type', sa.String(length=100), nullable=False),
    sa.Column('severity', sa.String(length=20), nullable=False),
    sa.Column('tier', sa.String(length=20), nullable=False),
    sa.Column('module', sa.String(length=20), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('body', sa.String(length=2000), nullable=False),
    sa.Column('entity_type', sa.String(length=30), nullable=True),
    sa.Column('entity_id', sa.Integer(), nullable=True),
    sa.Column('branch', sa.String(length=255), nullable=True),
    sa.Column('payload', sa.JSON(), nullable=False),
    sa.Column('dedupe_key', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_notification_events_branch'), 'notification_events', ['branch'], unique=False)
    op.create_index('ix_notification_events_created_at', 'notification_events', ['created_at'], unique=False)
    op.create_index(op.f('ix_notification_events_event_type'), 'notification_events', ['event_type'], unique=False)
    op.create_index(op.f('ix_notification_events_module'), 'notification_events', ['module'], unique=False)
    op.create_index('uq_notification_events_dedupe_key', 'notification_events', ['dedupe_key'], unique=True, postgresql_where=sa.text('dedupe_key IS NOT NULL'))
    op.create_table('notification_deliveries',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('event_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('channel', sa.String(length=20), server_default='in_app', nullable=False),
    sa.Column('status', sa.String(length=20), server_default='pending', nullable=False),
    sa.Column('external_id', sa.String(length=255), nullable=True),
    sa.Column('read_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['event_id'], ['notification_events.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_notification_deliveries_created_at', 'notification_deliveries', ['created_at'], unique=False)
    op.create_index(op.f('ix_notification_deliveries_event_id'), 'notification_deliveries', ['event_id'], unique=False)
    op.create_index(op.f('ix_notification_deliveries_user_id'), 'notification_deliveries', ['user_id'], unique=False)
    op.create_index('ix_notification_deliveries_user_read_created', 'notification_deliveries', ['user_id', 'read_at', 'created_at'], unique=False)
    op.create_table('notification_state',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('state_key', sa.String(length=255), nullable=False),
    sa.Column('state_value', sa.String(length=50), nullable=False),
    sa.Column('last_changed_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('last_event_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['last_event_id'], ['notification_events.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_notification_state_state_key'), 'notification_state', ['state_key'], unique=True)
    op.add_column('users', sa.Column('notification_tier', sa.String(length=20), server_default='operational', nullable=False))
    op.add_column('users', sa.Column('phone_number', sa.String(length=20), nullable=True))
    op.add_column('users', sa.Column('whatsapp_opted_in', sa.Boolean(), server_default=sa.text('false'), nullable=False))
    op.add_column('users', sa.Column('whatsapp_opted_in_at', sa.DateTime(timezone=True), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'whatsapp_opted_in_at')
    op.drop_column('users', 'whatsapp_opted_in')
    op.drop_column('users', 'phone_number')
    op.drop_column('users', 'notification_tier')
    op.drop_index(op.f('ix_notification_state_state_key'), table_name='notification_state')
    op.drop_table('notification_state')
    op.drop_index('ix_notification_deliveries_user_read_created', table_name='notification_deliveries')
    op.drop_index(op.f('ix_notification_deliveries_user_id'), table_name='notification_deliveries')
    op.drop_index(op.f('ix_notification_deliveries_event_id'), table_name='notification_deliveries')
    op.drop_index('ix_notification_deliveries_created_at', table_name='notification_deliveries')
    op.drop_table('notification_deliveries')
    op.drop_index('uq_notification_events_dedupe_key', table_name='notification_events', postgresql_where=sa.text('dedupe_key IS NOT NULL'))
    op.drop_index(op.f('ix_notification_events_module'), table_name='notification_events')
    op.drop_index(op.f('ix_notification_events_event_type'), table_name='notification_events')
    op.drop_index('ix_notification_events_created_at', table_name='notification_events')
    op.drop_index(op.f('ix_notification_events_branch'), table_name='notification_events')
    op.drop_table('notification_events')
    # ### end Alembic commands ###
