"""baseline

Revision ID: b9f72f7a8a7e
Revises:
Create Date: 2026-08-25 12:58:19.560942

Deliberately empty. The production database already has the current schema
(built by create_all() and loaded from Excel) — autogenerate confirms zero
drift against the models, so there is nothing to create here. This revision
exists only to give every environment a common starting point; run
`alembic stamp head` against an existing database (never `upgrade head`,
which would be a no-op anyway here but is the wrong verb for "this schema
already exists") and `alembic upgrade head` against a brand-new one.
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b9f72f7a8a7e'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
