"""notification fan-out queue column

Revision ID: e42775a85496
Revises: 8ad6b97f1997
Create Date: 2026-08-28 12:30:30.697698

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e42775a85496'
down_revision: Union[str, Sequence[str], None] = '8ad6b97f1997'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('notification_events', sa.Column('fanned_out_at', sa.DateTime(timezone=True), nullable=True))
    op.create_index('ix_notification_events_fanout_queue', 'notification_events', ['id'], unique=False, postgresql_where=sa.text('fanned_out_at IS NULL'))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_notification_events_fanout_queue', table_name='notification_events', postgresql_where=sa.text('fanned_out_at IS NULL'))
    op.drop_column('notification_events', 'fanned_out_at')
    # ### end Alembic commands ###
